version: 2.0

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: ./mvnw verify
      - store_test_results: # We use this timing data to optimize the future runs
          path: target/surefire-reports

workflows:
  version: 2

  build-then-test:
    jobs:
      - test
